version: '3.6'
services:
  default:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.template-web.rule=PathPrefix(`/template-web/`)'
